# fly.toml app configuration file generated for logistics-watcher-back on 2024-06-11T19:26:57-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'logistics-watcher-back'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 3005
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  
[[services]]
  internal_port = 3006
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    handlers = ["tls"]
    port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
